blank_issues_enabled: false
contact_links:
  - Name: Slack
    url: https://dockr.ly/comm-slack
    about: Ask questions in the Docker Community Slack
  - name: Moby
    url: https://github.com/moby/moby
    about: Bug reports for Docker Engine
  - name: Docker Desktop for Windows
    url: https://github.com/docker/for-win
    about: Bug reports for Docker Desktop for Windows 
  - name: Docker Desktop for Mac
    url: https://github.com/docker/for-mac
    about: Bug reports for Docker Desktop for Mac 
  - name: Docker Desktop for Linux
    url: https://github.com/docker/for-linux
    about: Bug reports for Docker Desktop for Linux 
  - name: Docker Compose
    url: https://github.com/docker/compose
    about: Bug reports for Docker Compose
